# Generated by Django 2.2 on 2024-03-01 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tibiauth', '0002_tibiuser_public_pem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tibiuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
