# Generated by Django 2.2 on 2023-11-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_connect', '0002_auto_20231011_1142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FedowNodeConfig',
        ),
    ]
