# Generated by Django 2.2 on 2021-04-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0002_auto_20210128_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportbar',
            name='monnaie_encaisse',
            field=models.FloatField(default=0, null=True, verbose_name='Bisiks encaissés'),
        ),
        migrations.AlterField(
            model_name='rapportbar',
            name='monnaie_vendu',
            field=models.FloatField(default=0, null=True, verbose_name='Bisiks vendus'),
        ),
    ]
