# Generated by Django 2.2 on 2021-04-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0003_auto_20210409_1048'),
    ]

    operations = [
    ]
