# Generated by Django 2.2 on 2021-04-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0004_auto_20210409_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appareil',
            name='periph',
            field=models.CharField(blank=True, choices=[('FOR', 'Front ordinateur'), ('FMO', 'Front smartphone'), ('FPI', 'Front Raspberry'), ('SSF', 'Serveur NFC sans front'), ('FSN', 'Front sans lecteur NFC')], max_length=3, null=True),
        ),
    ]
