# Generated by Django 2.2 on 2021-04-09 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0005_auto_20210409_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appairage',
            name='front',
            field=models.OneToOneField(limit_choices_to=models.Q(periph='FSN'), on_delete=django.db.models.deletion.CASCADE, related_name='appareillement_front', to='APIcashless.Appareil'),
        ),
        migrations.AlterField(
            model_name='appairage',
            name='lecteur_nfc',
            field=models.OneToOneField(limit_choices_to=models.Q(periph='SSF'), on_delete=django.db.models.deletion.CASCADE, related_name='appareillement_lecteur_nfc', to='APIcashless.Appareil'),
        ),
    ]
