# Generated by Django 2.2 on 2021-04-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0013_auto_20210409_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlevendu',
            name='depuis_fractionne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlevendu',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIcashless.Table'),
        ),
    ]
