# Generated by Django 2.2 on 2021-04-09 09:49

from django.db import migrations

def methode_paiement_oceco_commande(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Configuration = apps.get_model('APIcashless', 'Configuration')
    MoyenPaiement = apps.get_model('APIcashless', 'MoyenPaiement')
    configuration = Configuration.objects.get()

    oceco = MoyenPaiement.objects.get_or_create(name="Web (Oceco)", blockchain=False)[0]
    commande = MoyenPaiement.objects.get_or_create(name="Commande", blockchain=False)[0]

    configuration.moyen_paiement_oceco = oceco
    configuration.moyen_paiement_commande = commande

    configuration.save()

def reverse(apps, schema_editor):
    Configuration = apps.get_model('APIcashless', 'Configuration')
    MoyenPaiement = apps.get_model('APIcashless', 'MoyenPaiement')
    configuration = Configuration.objects.get()

    try:
        oceco = MoyenPaiement.objects.get(name="Web (Oceco)")
        oceco.delete()
    except:
        pass

    try:
        commande = MoyenPaiement.objects.get(name="Commande")
        commande.delete()
    except:
        pass



class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0019_methode_franctionne_20210409_1318'),
    ]

    operations = [
            migrations.RunPython(methode_paiement_oceco_commande, reverse),
    ]
