# Generated by Django 2.2 on 2021-04-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0023_derniere_action_membre_20210416_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportbar',
            name='monnaie_encaisse',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rapportbar',
            name='monnaie_vendu',
            field=models.FloatField(default=0, null=True),
        ),
    ]
