# Generated by Django 2.2 on 2021-04-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0028_check_permissions_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecommandesauvegarde',
            name='statut',
            field=models.CharField(choices=[('PP', 'En préparation'), ('PR', 'Prêt à servir'), ('SV', 'Servis'), ('PY', 'Payés'), ('SP', 'Servis et payés'), ('CA', 'Annulés')], default='PP', max_length=2),
        ),
        migrations.AlterField(
            model_name='commandesauvegarde',
            name='statut',
            field=models.CharField(choices=[('O', 'Ouverte'), ('S', 'Servie'), ('P', 'Payée'), ('SP', 'Servie et payée'), ('CA', 'Annulée')], default='O', max_length=2),
        ),
    ]
