# Generated by Django 2.2 on 2021-05-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0030_groupementcategorie_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='taux_tva',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
