# Generated by Django 2.2 on 2021-05-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0031_auto_20210506_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointdevente',
            name='poid_liste',
            field=models.IntegerField(default=0, verbose_name='Poids'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='poid_liste',
            field=models.IntegerField(default=0, verbose_name='Poids'),
        ),
    ]
