# Generated by Django 2.2 on 2021-05-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0033_auto_20210506_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='statut',
            field=models.CharField(choices=[('L', 'Libre'), ('O', 'Occupée')], default='L', max_length=1),
        ),
    ]
