# Generated by Django 2.2 on 2021-05-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0037_groupementcategorie_thermal_printer_ip_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupementcategorie',
            name='thermal_printer_ip_adress',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name="Adresse ip de l'imprimante réseau corespondante"),
        ),
    ]
