# Generated by Django 2.2 on 2021-05-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0038_auto_20210513_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupementcategorie',
            name='thermal_printer_ip_adress',
        ),
        migrations.AddField(
            model_name='groupementcategorie',
            name='thermal_printer_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Nom de l'imprimante CUPS"),
        ),
    ]
