# Generated by Django 2.2 on 2021-05-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0044_auto_20210516_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartemaitresse',
            name='edit_mode',
            field=models.BooleanField(default=False, verbose_name='Mode gérant.e'),
        ),
    ]
