# Generated by Django 2.2 on 2021-05-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0047_auto_20210523_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupementcategorie',
            options={'verbose_name': 'Groupement pour préparation', 'verbose_name_plural': 'Groupements pour préparation'},
        ),
        migrations.AddField(
            model_name='table',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
