# Generated by Django 2.2 on 2021-05-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0052_groupementcategorie_activer_impression'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='api_print',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='serveur_impression',
        ),
    ]
