# Generated by Django 2.2 on 2021-05-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0055_auto_20210524_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupementcategorie',
            name='compteur_ticket_journee',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Compteur de ticket'),
        ),
    ]
