# Generated by Django 2.2 on 2021-05-24 06:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0056_groupementcategorie_compteur_ticket_journee'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandesauvegarde',
            name='numero_du_ticket_imprime',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
