# Generated by Django 2.2 on 2021-06-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0062_auto_20210608_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='validation_service_ecran',
            field=models.BooleanField(default=True, verbose_name='Validation sur ecran de préparation'),
        ),
    ]
