# Generated by Django 2.2 on 2021-06-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0063_auto_20210608_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='validation_service_ecran',
            field=models.BooleanField(default=True, verbose_name='Validation manuelle de la préparation sur ecran tactile'),
        ),
    ]
