# Generated by Django 2.2 on 2021-06-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0064_auto_20210611_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='remboursement_auto_annulation',
            field=models.BooleanField(default=False, verbose_name="Si annulation d'un article déja payé par cashless, on rembourse automatiquement sur la carte"),
        ),
    ]
