# Generated by Django 2.2 on 2021-07-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0069_auto_20210714_1349'),
        ('APIcashless', '0071_rapportpointsdevente_remboursement_monnaie_espece'),
    ]

    operations = [
    ]
