# Generated by Django 2.2 on 2021-07-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0072_merge_20210727_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapportpointsdevente',
            options={'ordering': ('-date',), 'verbose_name': 'R. Points de vente', 'verbose_name_plural': 'R. Points de ventes'},
        ),
        migrations.AlterField(
            model_name='rapportfinancierglobal',
            name='recharge_monnaie_cashless_cadeau_depuis_oceco',
            field=models.FloatField(default=0, verbose_name='Recharge OCECO'),
        ),
        migrations.AlterField(
            model_name='rapportpointsdevente',
            name='articles_offerts',
            field=models.FloatField(default=0, verbose_name='Offert'),
        ),
        migrations.AlterField(
            model_name='rapportpointsdevente',
            name='vente_directe_en_carte_bancaire',
            field=models.FloatField(default=0, verbose_name='CB'),
        ),
        migrations.AlterField(
            model_name='rapportpointsdevente',
            name='vente_directe_en_espece',
            field=models.FloatField(default=0, verbose_name='Espece'),
        ),
        migrations.AlterField(
            model_name='rapportpointsdevente',
            name='vente_en_monnaie_cashless',
            field=models.FloatField(default=0, verbose_name='Cashless'),
        ),
        migrations.AlterField(
            model_name='rapportpointsdevente',
            name='vente_en_monnaie_cashless_cadeau',
            field=models.FloatField(default=0, verbose_name='Cadeau'),
        ),
    ]
