# Generated by Django 2.2 on 2021-07-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0073_auto_20210728_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='cashless',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articles',
            name='categorie',
            field=models.ForeignKey(blank=True, help_text='Seule les catégories Bière, Boissons et Restauration seront affiché dans les pages de préaparation CUISINE ET BAR', null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIcashless.Categorie'),
        ),
        migrations.AlterField(
            model_name='pointdevente',
            name='comportement',
            field=models.CharField(choices=[('A', 'Vente'), ('C', 'Rechargement')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='rapportfinancierglobal',
            name='recharge_monnaie_cashless',
            field=models.FloatField(default=0, verbose_name='R. Cashless'),
        ),
        migrations.AlterField(
            model_name='rapportfinancierglobal',
            name='recharge_monnaie_cashless_cadeau',
            field=models.FloatField(default=0, verbose_name='R. Cadeau'),
        ),
        migrations.AlterField(
            model_name='rapportfinancierglobal',
            name='recharge_monnaie_cashless_cadeau_depuis_oceco',
            field=models.FloatField(default=0, verbose_name='R. OCECO'),
        ),
        migrations.AlterField(
            model_name='rapportfinancierglobal',
            name='remboursement_monnaie_espece',
            field=models.FloatField(default=0, verbose_name='Remb.'),
        ),
        migrations.AlterField(
            model_name='rapportfinancierglobal',
            name='total_vente_en_monnaie_cashless',
            field=models.FloatField(default=0, verbose_name='D. Cashless'),
        ),
        migrations.AlterField(
            model_name='rapportfinancierglobal',
            name='total_vente_en_monnaie_cashless_cadeau',
            field=models.FloatField(default=0, verbose_name='D. Cadeau'),
        ),
    ]
