# Generated by Django 2.2 on 2021-07-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0075_auto_20210728_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportfinancierglobal',
            name='total_benefice_estime',
            field=models.FloatField(default=0),
        ),
    ]
