# Generated by Django 2.2 on 2021-07-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0076_rapportfinancierglobal_total_benefice_estime'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportarticlesvendu',
            name='total_benefice_estime',
            field=models.FloatField(default=0),
        ),
    ]
