# Generated by Django 2.2 on 2021-09-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0078_auto_20210902_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointdevente',
            name='service_direct',
            field=models.BooleanField(default=True, verbose_name='Service direct ( vente au comptoir )'),
        ),
    ]
