# Generated by Django 2.2 on 2021-09-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0081_auto_20210926_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='adhesion_origine',
            field=models.CharField(choices=[('A', 'Admin'), ('F', 'Front Cashless'), ('Q', 'Scan QR Code'), ('B', 'Billetterie')], default='A', max_length=1, verbose_name='Origine Adhésion'),
        ),
    ]
