# Generated by Django 2.2 on 2021-10-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0090_auto_20211006_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapporttableaucomptable_pos',
            name='moyen_paiement',
        ),
        migrations.RemoveField(
            model_name='rapporttableaucomptable_pos',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='rapporttableaucomptable_pos',
            name='rapport',
        ),
        migrations.DeleteModel(
            name='RapportTableauComptable',
        ),
        migrations.DeleteModel(
            name='RapportTableauComptable_POS',
        ),
    ]
