# Generated by Django 2.2 on 2021-10-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0093_merge_20211012_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapporttableaucomptable',
            name='cout_estime',
            field=models.FloatField(default=0),
        ),
    ]
