# Generated by Django 2.2 on 2021-10-13 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0094_rapporttableaucomptable_cout_estime'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportarticlesvendu',
            name='pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='APIcashless.PointDeVente'),
        ),
    ]
