# Generated by Django 2.2 on 2021-10-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0098_configuration_url_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='domaine_cashless',
            field=models.URLField(blank=True, null=True),
        ),
    ]
