# Generated by Django 2.2 on 2021-11-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0100_rapporttableaucomptable_monnaie_restante_calcul_rapport'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapporttableaucomptable',
            name='cadeau_restant_calcul_rapport',
            field=models.FloatField(default=0),
        ),
    ]
