# Generated by Django 2.2 on 2021-11-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0102_delete_rapportbar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RapportFinancierGlobal',
        ),
        migrations.DeleteModel(
            name='RapportPointsDeVente',
        ),
    ]
