# Generated by Django 2.2 on 2021-11-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0103_auto_20211106_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='adhesion_suspendue',
            field=models.BooleanField(default=False),
        ),
    ]
