# Generated by Django 2.2 on 2021-11-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0104_configuration_adhesion_suspendue'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartecashless',
            name='adhesion_suspendue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='adhesion_suspendue',
            field=models.BooleanField(default=False, help_text='Adhésion possible sur carte sans membre. Au prix par default dès que la fiche membre est renseignée.'),
        ),
    ]
