# Generated by Django 2.2 on 2021-11-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0105_auto_20211122_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartecashless',
            name='adhesion_suspendue_paiement',
            field=models.CharField(choices=[('N', 'Aucune'), ('A', 'Carte Bancaire'), ('C', 'Espèce')], default='N', max_length=1),
        ),
    ]
