# Generated by Django 2.2 on 2021-12-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0106_cartecashless_adhesion_suspendue_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartecashless',
            name='adhesion_suspendue_paiement',
            field=models.CharField(choices=[('N', 'Aucune'), ('A', 'Carte Bancaire'), ('C', 'Espèce'), ('F', 'Gratuit')], default='N', max_length=1),
        ),
    ]
