# Generated by Django 2.2 on 2022-03-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0112_configuration_odoo_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='odoo_active',
            field=models.BooleanField(default=False, verbose_name='Envoyer vers Odoo'),
        ),
    ]
