# Generated by Django 2.2 on 2022-03-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0113_configuration_odoo_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='odoo_active',
        ),
        migrations.AddField(
            model_name='configuration',
            name='odoo_send_membership',
            field=models.BooleanField(default=False, verbose_name='Envoyer les adhésions vers Odoo'),
        ),
    ]
