# Generated by Django 2.2 on 2022-04-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0115_auto_20220330_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='journal_odoo_cb',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du journal Carte Bancaire'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='journal_odoo_espece',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du journal Espèce'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='journal_odoo_stripe',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du journal Stripe'),
        ),
    ]
