# Generated by Django 2.2 on 2022-07-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0117_auto_20220701_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='methode_choices',
            field=models.CharField(choices=[('VT', 'Vente'), ('RS', 'RechargeS'), ('RE', 'Recharge €'), ('RC', 'Recharge Cadeau'), ('AD', 'Adhésions'), ('CR', 'Retour de consigne'), ('VC', 'Vider Carte'), ('BC', 'Blanchir Carte'), ('VV', 'Void Carte'), ('FR', 'Fractionné'), ('BI', 'Billet de concert')], default='VT', max_length=2),
        ),
    ]
