# Generated by Django 2.2 on 2022-07-28 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0118_auto_20220711_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlevendu',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7be1d31b-b411-4256-b36d-54e91f4f304d')),
        ),
        migrations.AddField(
            model_name='configuration',
            name='revoquer_odoo_api_key',
            field=models.BooleanField(default=False, help_text='Selectionnez et validez supprimer une clé API et en entrer une nouvelle.', verbose_name='Révoquer'),
        ),
    ]
