# Generated by Django 2.2 on 2022-08-12 14:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('epsonprinter', '0002_printer_usb_adress'),
        ('APIcashless', '0119_auto_20220728_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupementcategorie',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epsonprinter.Printer', verbose_name='Imprimante'),
        ),
        migrations.AlterField(
            model_name='articlevendu',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2854ff11-e948-4eee-91d6-db80dd1587e4')),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='revoquer_odoo_api_key',
            field=models.BooleanField(default=False, help_text='Selectionnez et validez pour supprimer la clé API et entrer une nouvelle.', verbose_name='Révoquer la clé API'),
        ),
    ]
