# Generated by Django 2.2 on 2022-08-16 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0120_auto_20220812_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlevendu',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
