# Generated by Django 2.2 on 2022-08-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0127_auto_20220825_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='pied_ticket',
            field=models.TextField(blank=True, null=True),
        ),
    ]
