# Generated by Django 2.2 on 2022-09-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0128_auto_20220829_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecommandesauvegarde',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='articlecommandesauvegarde',
            name='reste_a_payer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='articlecommandesauvegarde',
            name='reste_a_servir',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
