# Generated by Django 2.2 on 2022-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0130_auto_20220922_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointdevente',
            name='accepte_commandes',
            field=models.BooleanField(default=True),
        ),
    ]
