# Generated by Django 2.2 on 2022-09-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0132_auto_20220923_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='cashback_start',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='cashback_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
