# Generated by Django 2.2 on 2022-09-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0133_auto_20220924_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='cashback_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='cashback_start',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Valeur du rechargement en ligne à partir de laquelle les cadeaux s'enclenchent", max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='cashback_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valeur donnée en monnaie cadeau', max_digits=7, null=True),
        ),
    ]
