# Generated by Django 2.2 on 2022-10-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0140_auto_20221031_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='billetterie_url',
            field=models.URLField(blank=True, null=True, verbose_name='Url du serveur SaaS'),
        ),
    ]
