# Generated by Django 2.2 on 2023-01-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0144_auto_20230102_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='billetterie_url',
            field=models.URLField(default='https://www.tibillet.re/', verbose_name='Url du serveur SaaS'),
        ),
    ]
