# Generated by Django 2.2 on 2023-01-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0146_auto_20230102_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='asset_categorie',
            field=models.CharField(choices=[('LTE', 'Token local €'), ('LTG', 'Token local cadeau'), ('FED', 'Token Federated Stripe'), ('CSH', 'Espèces'), ('CCB', 'Carte bancaire TPE')], default='LTE', max_length=3),
        ),
        migrations.AlterField(
            model_name='articles',
            name='methode_choices',
            field=models.CharField(choices=[('VT', 'Vente'), ('RE', 'Recharge €'), ('RF', 'Recharge fédérée €'), ('RC', 'Recharge Cadeau'), ('AD', 'Adhésions'), ('CR', 'Retour de consigne'), ('VC', 'Vider Carte'), ('BC', 'Blanchir Carte'), ('VV', 'Void Carte'), ('FR', 'Fractionné'), ('BI', 'Billet de concert')], default='VT', max_length=2),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='domaine_cashless',
            field=models.URLField(default='https://test.cashless.tibillet.localhost/'),
        ),
    ]
