# Generated by Django 2.2 on 2023-01-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0148_auto_20230120_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyenpaiement',
            name='categorie',
            field=models.CharField(choices=[('LE', 'Token local €'), ('LG', 'Token local cadeau'), ('FR', 'Fractionné'), ('AR', 'Ardoise'), ('SF', 'Token Federated Stripe'), ('SN', 'Stripe no federated'), ('CA', 'Espèces'), ('CC', 'Carte bancaire TPE'), ('OC', 'Oceco')], default='LE', max_length=2),
        ),
    ]
