# Generated by Django 2.2 on 2023-01-20 09:05

from django.db import migrations

# from APIcashless.models import Configuration, MoyenPaiement


def set_categorie_to_moyen_paiement(apps, schema_editor):
    # Déplacé au 0160, sinon crashais car Configuration n'est pas a jour ....

    pass

def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0149_auto_20230120_1323'),
    ]

    operations = [
        migrations.RunPython(set_categorie_to_moyen_paiement, reverse),
    ]
