# Generated by Django 2.2 on 2023-02-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0153_rapporttableaucomptable_chiffre_affaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlevendu',
            name='qty',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, null=True),
        ),
    ]
