# Generated by Django 2.2 on 2023-02-26 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0154_auto_20230223_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='chainname',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='rpchost',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='rpcpasswd',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='rpcport',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='rpcuser',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='username',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='walletLocation',
        ),
    ]
