# Generated by Django 2.2 on 2023-03-01 12:37

from django.db import migrations

def add_taux_tva(apps, schema_editor):
    TauxTVA = apps.get_model('APIcashless', 'TauxTVA')
    TauxTVA.objects.get_or_create(
        name="Restauration 2.1",
        taux=2.1
    )
    TauxTVA.objects.get_or_create(
        name="Alcool 8.5",
        taux=8.5
    )

    ArticleVendu = apps.get_model('APIcashless', 'ArticleVendu')
    print("")
    print("ajout des taux de TVA sur les articles déja vendus. Cela prendre un peu de temps...")
    print("...")

    for article in ArticleVendu.objects.all():
        if article.article:
            if article.article.categorie:
                if article.article.categorie.tva:
                    article.tva = article.article.categorie.tva.taux
                    article.save()

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0155_auto_20230226_0809'),
    ]

    operations = [
        migrations.RunPython(add_taux_tva, reverse),
    ]

