# Generated by Django 2.2 on 2023-03-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0156_add_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='is_sync',
            field=models.BooleanField(default=True),
        ),
    ]
