# Generated by Django 2.2 on 2023-04-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0159_rapporttableaucomptable_cash_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyenpaiement',
            name='categorie',
            field=models.CharField(choices=[('LE', 'Token local €'), ('LG', 'Token local cadeau'), ('FR', 'Fractionné'), ('SF', 'Token Federated Stripe'), ('SN', 'Stripe no federated'), ('CA', 'Espèces'), ('CC', 'Carte bancaire TPE'), ('CH', 'Cheque'), ('OC', 'Oceco'), ('AR', 'Ardoise'), ('CM', 'Commande')], default='LE', max_length=2),
        ),
    ]
