# Generated by Django 2.2 on 2023-05-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0162_assert_all_moyen_paiement_MANUAL_20230423_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlevendu',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='APIcashless.Categorie'),
        ),
    ]
