# Generated by Django 2.2 on 2023-06-19 09:42

from django.db import migrations
from django.core.management import call_command

from APIcashless.models import Articles, ArticleVendu


def set_prix_achat_to_articlevendu(apps, schema_editor):
        pass
        # for article in Articles.objects.all():
        #     ArticleVendu.objects.filter(article=article).update(prix_achat=article.prix_achat)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0165_articlevendu_prix_achat'),
    ]

    operations = [
        # Plus besoin
        # migrations.RunPython(set_prix_achat_to_articlevendu, reverse),
    ]
