# Generated by Django 2.2 on 2023-07-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0166_MANUAL_auto_20230619_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='cloture_de_caisse_auto',
            field=models.TimeField(blank=True, default='04:00:00', null=True, verbose_name='Heure de cloture automatique de toutes les caisses'),
        ),
        migrations.DeleteModel(
            name='RapportTableauComptable_POS',
        ),
    ]
