# Generated by Django 2.2 on 2023-07-13 10:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0167_auto_20230713_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClotureCaisse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('ticketZ', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
