# Generated by Django 2.2 on 2023-07-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0168_cloturecaisse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloturecaisse',
            options={'verbose_name': 'Cloture de caisse', 'verbose_name_plural': 'Clotures de caisses'},
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Généré le'),
        ),
    ]
