# Generated by Django 2.2 on 2023-07-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0171_auto_20230718_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloturecaisse',
            options={'ordering': ('-datetime',), 'verbose_name': 'Cloture de caisse', 'verbose_name_plural': 'Clotures de caisses'},
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='categorie',
            field=models.CharField(choices=[('C', 'Cloture de caisse'), ('H', 'Rapport hebdomadaire'), ('M', 'Rapport mensuel'), ('A', 'Rapport annuel')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='end',
            field=models.DateTimeField(verbose_name='Fermeture de caisse'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='start',
            field=models.DateTimeField(verbose_name='Ouverture de caisse'),
        ),
    ]
