# Generated by Django 2.2 on 2023-07-18 15:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0172_auto_20230718_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloturecaisse',
            options={'ordering': ('-datetime',), 'verbose_name': 'Rapport et cloture de caisse', 'verbose_name_plural': 'Rapports et clotures de caisses'},
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='end',
            field=models.DateTimeField(verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='start',
            field=models.DateTimeField(verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='ticketZ',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, max_length=50000),
        ),
    ]
