# Generated by Django 2.2 on 2023-08-17 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
        ('APIcashless', '0176_auto_20230727_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='fedow_domain',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='fedow_ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='fedow_key',
            field=models.CharField(blank=True, editable=False, max_length=41, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='fedow_place_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='ip_cashless',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP publique du serveur cashless'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='onboard_url',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='Validez votre compte stripe :'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='self_fed_apikey',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_framework_api_key.APIKey'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='string_connect',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Entrez la clé FEDOW pour activer le modèle fédéré :'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stripe_connect_account',
            field=models.CharField(blank=True, editable=False, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='stripe_connect_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='domaine_cashless',
            field=models.URLField(default='https://test.cashless.tibillet.localhost/', verbose_name='Url publique du serveur cashless'),
        ),
    ]
