# Generated by Django 2.2 on 2023-10-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0181_auto_20230825_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartecashless',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True, verbose_name='Numéro imprimé'),
        ),
        migrations.AlterField(
            model_name='cartecashless',
            name='tag_id',
            field=models.CharField(db_index=True, max_length=8, unique=True, verbose_name='RFID First TagID'),
        ),
        migrations.AlterField(
            model_name='cartecashless',
            name='uuid_qrcode',
            field=models.UUIDField(blank=True, null=True, verbose_name='QrCode Uuid'),
        ),
    ]
