# Generated by Django 2.2 on 2023-10-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0182_auto_20231006_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='fedow_api_key',
            new_name='fedow_place_admin_apikey',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='fedow_public_rsa_key',
            new_name='fedow_place_wallet_public_pem',
        ),
    ]
