# Generated by Django 2.2 on 2023-10-11 09:08

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0184_auto_20231006_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField()),
                ('img', stdimage.models.JPEGField(blank=True, force_min_size=False, null=True, upload_to='images/', validators=[stdimage.validators.MinSizeValidator(720, 720), stdimage.validators.MaxSizeValidator(1920, 1920)], variations={'crop': (480, 270, True), 'hdr': (720, 720), 'med': (480, 480), 'thumbnail': (150, 90)}, verbose_name='img')),
            ],
        ),
        migrations.AddField(
            model_name='cartecashless',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='APIcashless.Origin'),
        ),
    ]
