# Generated by Django 2.2 on 2023-10-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0188_moyenpaiement_currency_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='federated_currency',
        ),
    ]
