# Generated by Django 2.2 on 2023-12-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0192_membre_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlevendu',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='cle_dokos',
            field=models.CharField(blank=True, help_text='Format pub_key:priv_key', max_length=200, null=True, verbose_name='Clé API Dokos'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='id_lieu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Id du lieu Dokos (client_venue)'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='url_dokos',
            field=models.URLField(blank=True, null=True, verbose_name='Url du serveur Dokos'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='methode_choices',
            field=models.CharField(choices=[('VT', 'Vente'), ('RE', 'Recharge €'), ('RF', 'Recharge fédérée €'), ('RC', 'Recharge Cadeau'), ('AD', 'Adhésions'), ('CR', 'Retour de consigne'), ('VC', 'Vider Carte'), ('BC', 'Blanchir Carte'), ('VV', 'Void Carte'), ('FR', 'Fractionné'), ('BI', 'Billet de concert'), ('BG', 'Badgeuse')], default='VT', max_length=2),
        ),
    ]
