# Generated by Django 2.2 on 2023-12-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0193_auto_20231204_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='revoquer_dokos',
            field=models.BooleanField(default=False, help_text='Selectionnez et validez pour supprimer la clé API et entrer une nouvelle.', verbose_name='Révoquer la clé Dokos'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='url_dokos',
            field=models.URLField(blank=True, help_text='ex: http://demobadge.dokos.cloud/', null=True, verbose_name='Url du serveur Dokos'),
        ),
    ]
