# Generated by Django 2.2 on 2023-12-22 10:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0195_auto_20231212_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Nom')),
                ('dokos_id', models.CharField(blank=True, max_length=50, null=True)),
                ('stripe_connect_valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='id_lieu',
            new_name='dokos_id',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='cle_dokos',
            new_name='dokos_key',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='url_dokos',
            new_name='dokos_url',
        ),
        migrations.AlterField(
            model_name='origin',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origins', to='APIcashless.Place'),
        ),
        migrations.AddField(
            model_name='place',
            name='wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='place', to='APIcashless.Wallet'),
        ),
        migrations.AddField(
            model_name='moyenpaiement',
            name='place_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moyen_paiements', to='APIcashless.Place'),
        ),
    ]
