# Generated by Django 2.2 on 2023-12-22 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0197_remove_cartecashless_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartecashless',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='APIcashless.Wallet'),
        ),
    ]
