# Generated by Django 2.2 on 2024-01-02 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0200_membre_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='subscription_fedow_asset',
            field=models.ForeignKey(blank=True, help_text='Asset Fedow utilisé pour un abonnement, adhésion ou une badgeuse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_articles', to='APIcashless.MoyenPaiement'),
        ),
    ]
