# Generated by Django 2.2 on 2024-01-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0206_auto_20240122_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartecashless',
            name='number',
            field=models.CharField(blank=True, db_index=True, help_text='Non obligatoire lors de la création, il sera généré aléatoirement si non rempli.', max_length=8, null=True, unique=True, verbose_name='Numéro imprimé'),
        ),
        migrations.AlterField(
            model_name='cartecashless',
            name='tag_id',
            field=models.CharField(db_index=True, max_length=8, unique=True, verbose_name='First TagID (8)'),
        ),
        migrations.AlterField(
            model_name='cartecashless',
            name='uuid_qrcode',
            field=models.UUIDField(blank=True, help_text='Non obligatoire lors de la création, il sera généré aléatoirement si non rempli.', null=True, verbose_name='uuid4 pour QrCode'),
        ),
    ]
