# Generated by Django 2.2 on 2024-01-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0208_articlevendu_hash_fedow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlevendu',
            options={'ordering': ('-date_time',), 'verbose_name': 'Article vendu', 'verbose_name_plural': 'Articles vendus'},
        ),
        migrations.AlterModelOptions(
            name='cloturecaisse',
            options={'ordering': ('-datetime',), 'verbose_name': 'Cloture de caisse', 'verbose_name_plural': 'Clotures de caisse'},
        ),
    ]
