# Generated by Django 2.2 on 2024-01-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0211_MANUAL_ASSET_FIDELITY_20240130_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='fidelity_active',
            field=models.BooleanField(default=False, verbose_name='Incrémentez des points de fidélité pour chaque achat.'),
        ),
    ]
