# Generated by Django 2.2 on 2024-02-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0215_auto_20240209_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='fedow_place_wallet_public_pem',
        ),
        migrations.AlterField(
            model_name='configuration',
            name='badgeuse_active',
            field=models.BooleanField(default=False, help_text="Création de l'article et du points de vente Badge si activé.", verbose_name='Badgeuse active'),
        ),
    ]
