# Generated by Django 2.2 on 2024-02-23 09:18
from django.core.management import call_command
from django.db import migrations

def check_permission(apps, schema_editor):
    # call_command('check_permissions')
    pass

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0218_auto_20240222_1845'),
    ]

    operations = [
        migrations.RunPython(check_permission, reverse),
    ]

