# Generated by Django 2.2 on 2024-05-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0226_auto_20240514_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyenpaiement',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
