# Generated by Django 2.2 on 2024-05-27 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0229_articles_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='choice_adhesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIcashless.Articles'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='methode_choices',
            field=models.CharField(choices=[('VT', 'Vente'), ('RE', 'Recharge €'), ('RF', 'Recharge fédérée €'), ('RC', 'Recharge Cadeau'), ('AD', 'Adhésions'), ('CR', 'Retour de consigne'), ('VC', 'Vider Carte'), ('VV', 'Void Carte'), ('FR', 'Fractionné'), ('BI', 'Billet de concert'), ('BG', 'Badgeuse'), ('FD', 'Fidélité')], default='VT', max_length=2),
        ),
    ]
