# Generated by Django 2.2 on 2024-06-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0231_auto_20240527_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlevendu',
            options={'ordering': ('-date_time',), 'verbose_name': 'Vente', 'verbose_name_plural': 'Ventes'},
        ),
    ]
