# Generated by Django 2.2 on 2024-08-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0234_auto_20240822_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartecashless',
            name='tag_id',
            field=models.CharField(db_index=True, max_length=8, unique=True, verbose_name='RFID TagID (8)'),
        ),
    ]
