# Generated by Django 2.2 on 2024-10-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0235_auto_20240823_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointdevente',
            name='accepte_cheque',
            field=models.BooleanField(default=False),
        ),
    ]
