# Generated by Django 2.2 on 2024-10-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0236_pointdevente_accepte_cheque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membre',
            options={'ordering': ('-date_ajout',), 'verbose_name': 'Membre responsable', 'verbose_name_plural': 'Membres responsables'},
        ),
        migrations.AlterField(
            model_name='cartemaitresse',
            name='carte',
            field=models.ForeignKey(help_text='Seul les cartes avec membres sont listées ici.', on_delete=django.db.models.deletion.CASCADE, related_name='cartes_maitresses', to='APIcashless.CarteCashless', unique=True),
        ),
    ]
