# Generated by Django 2.2 on 2024-10-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0237_auto_20241019_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='appareillement',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='pin_code_primary_link',
        ),
        migrations.AlterField(
            model_name='configuration',
            name='validation_service_ecran',
            field=models.BooleanField(default=False, verbose_name='Validation manuelle de la préparation sur ecran tactile'),
        ),
    ]
