# Generated by Django 2.2 on 2024-10-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0238_auto_20241023_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nom'),
        ),
    ]
