# Generated by Django 2.2 on 2024-11-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0241_auto_20241121_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='methode_choices',
            field=models.CharField(choices=[('VT', 'Vente'), ('RE', 'Recharge €'), ('RF', 'Recharge fédérée €'), ('RC', 'Recharge Cadeau'), ('AD', 'Adhésions'), ('CR', 'Retour de consigne'), ('VC', 'Vider Carte'), ('VV', 'Void Carte'), ('FR', 'Fractionné'), ('BI', 'Billet de concert'), ('BG', 'Badgeuse'), ('FD', 'Fidélité'), ('HB', 'Cashback')], default='VT', max_length=2, verbose_name='methode'),
        ),
    ]
