# Generated by Django 2.2 on 2024-11-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0242_auto_20241124_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='subscription_fedow_asset',
            new_name='fedow_asset',
        ),
    ]
