# Generated by Django 2.2 on 2025-01-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0245_auto_20241129_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupementcategorie',
            options={'verbose_name': 'Préparation & impression', 'verbose_name_plural': 'Préparations & impressions'},
        ),
        migrations.AlterField(
            model_name='configuration',
            name='cash_float',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fond de caisse par défaut'),
        ),
    ]
