# Generated by Django 2.2 on 2024-12-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0246_auto_20241206_0841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupementcategorie',
            options={'verbose_name': "Groupe d'impression", 'verbose_name_plural': "Groupes d'impression"},
        ),
        migrations.AddField(
            model_name='groupementcategorie',
            name='pos',
            field=models.ManyToManyField(blank=True, help_text='Si vide : tous les points de ventes. Si non, uniquement les selectionnés', to='APIcashless.PointDeVente', verbose_name='Points de vente'),
        ),
    ]
