# Generated by Django 2.2 on 2024-12-22 09:30

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _



def create_free_asset(apps, schema_editor):
        MoyenPaiement = apps.get_model('APIcashless', 'MoyenPaiement')
        try :
            free_asset = MoyenPaiement.objects.get(categorie='NA')
        except MoyenPaiement.DoesNotExist:
            free_asset = MoyenPaiement.objects.create(categorie='NA', name=_("Offert"))


def reverse(apps, schema_editor):
    MoyenPaiement = apps.get_model('APIcashless', 'MoyenPaiement')
    try:
        free_asset = MoyenPaiement.objects.get(categorie='NA')
        free_asset.delete()
    except MoyenPaiement.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0247_auto_20241214_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyenpaiement',
            name='categorie',
            field=models.CharField(choices=[('LE', 'Token local €'), ('LG', 'Token local cadeau'), ('XE', 'Token fédéré exterieur €'), ('XG', 'Token fédéré cadeau'), ('FD', 'Fedow'), ('CA', 'Espèces'), ('CC', 'Carte bancaire'), ('CH', 'Cheque'), ('NA', 'Offert'), ('FR', 'Fractionné'), ('CM', 'Commande'), ('AR', 'Ardoise'), ('SN', 'Stripe'), ('SF', 'Stripe (fedéré)'), ('OC', 'Oceco'), ('BG', 'Badgeuse'), ('XB', 'Badgeuse fédérée'), ('TP', 'Temps'), ('XT', 'Temps fédéré'), ('AD', 'Adhésion associative'), ('MS', 'Abonnement'), ('XM', 'Abonnement fédéré'), ('FI', 'Points de fidélité'), ('XF', 'Points de fidélité fédérés')], default='LE', max_length=2),
        ),

        migrations.RunPython(create_free_asset, reverse),

    ]


