# Generated by Django 2.2 on 2025-01-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0248_auto_20241222_1030'),
        ('APIcashless', '0246_auto_20250119_1304'),
    ]

    operations = [
    ]
