# Generated by Django 2.2 on 2024-12-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0248_auto_20241206_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appareil',
            name='periph',
            field=models.CharField(blank=True, choices=[('FOR', 'Front ordinateur'), ('FMO', 'Front smartphone'), ('SUN', 'Sunmi avec imprimante'), ('FPI', 'Front Raspberry'), ('SSF', 'Serveur NFC sans front'), ('FSN', 'Front sans lecteur NFC')], max_length=3, null=True),
        ),
    ]
