# Generated by Django 2.2 on 2025-02-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0250_auto_20250128_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyenpaiement',
            name='categorie',
            field=models.CharField(choices=[('LE', 'Local'), ('LG', 'Token cadeau'), ('XE', 'Externe'), ('XG', 'Token exterieur cadeau'), ('FD', 'Fedow'), ('CA', 'Espèces'), ('CC', 'Carte bancaire'), ('CH', 'Chèque'), ('NA', 'Offert'), ('FR', 'Fractionné'), ('CM', 'Commande'), ('AR', 'Ardoise'), ('SN', 'En ligne'), ('SF', 'Fédéré'), ('OC', 'Oceco'), ('BG', 'Badgeuse'), ('XB', 'Badgeuse fédérée'), ('TP', 'Temps'), ('XT', 'Temps fédéré'), ('AD', 'Adhésion associative'), ('MS', 'Abonnement'), ('XM', 'Abonnement fédéré'), ('FI', 'Points de fidélité'), ('XF', 'Points de fidélité fédérés')], default='LE', max_length=2),
        ),
    ]
