# Generated by Django 2.2 on 2025-03-21 16:10
from django.db import migrations, models

def create_banktransfert_mp(apps, schema_editor):
        MoyenPaiement = apps.get_model('APIcashless', 'MoyenPaiement')
        try :
            bank_transfer = MoyenPaiement.objects.get(categorie='TR')
        except MoyenPaiement.DoesNotExist:
            bank_transfer = MoyenPaiement.objects.create(name="Virement bancaire", blockchain=False, categorie='TR')


def reverse(apps, schema_editor):
    MoyenPaiement = apps.get_model('APIcashless', 'MoyenPaiement')
    try:
        bank_transfer = MoyenPaiement.objects.get(categorie='TR')
        bank_transfer.delete()
    except MoyenPaiement.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0251_auto_20250227_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyenpaiement',
            name='categorie',
            field=models.CharField(choices=[('LE', 'Local'), ('LG', 'Token cadeau'), ('XE', 'Externe'), ('XG', 'Token exterieur cadeau'), ('FD', 'Fedow'), ('CA', 'Espèces'), ('CC', 'Carte bancaire'), ('CH', 'Chèque'), ('TR', 'Bank transfer'), ('NA', 'Offert'), ('FR', 'Fractionné'), ('CM', 'Commande'), ('AR', 'Ardoise'), ('SN', 'En ligne'), ('SF', 'Fédéré'), ('OC', 'Oceco'), ('BG', 'Badgeuse'), ('XB', 'Badgeuse fédérée'), ('TP', 'Temps'), ('XT', 'Temps fédéré'), ('AD', 'Adhésion associative'), ('MS', 'Abonnement'), ('XM', 'Abonnement fédéré'), ('FI', 'Points de fidélité'), ('XF', 'Points de fidélité fédérés')], default='LE', max_length=2),
        ),
        migrations.RunPython(create_banktransfert_mp, reverse),
    ]
