# Generated by Django 2.2 on 2025-05-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0254_auto_20250408_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointdevente',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
