# Generated by Django 2.2 on 2025-05-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0255_pointdevente_hidden'),
        ('APIcashless', '0249_auto_20241209_1507'),
    ]

    operations = [
    ]
