# Generated by Django 2.2.28 on 2025-06-03 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0257_auto_20250504_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationStripe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_mode_test', models.BooleanField(default=True)),
                ('stripe_api_key', models.CharField(blank=True, max_length=250, null=True)),
                ('stripe_connect_account', models.CharField(blank=True, max_length=21, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom')),
                ('stripe_id', models.CharField(blank=True, max_length=21, null=True, verbose_name='Stripe ID')),
                ('is_primary_location', models.BooleanField(default=False, verbose_name='Primary Asset Location')),
            ],
        ),
        migrations.AddField(
            model_name='configuration',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='registration_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Code d'enregistrement du lecteur"),
        ),
    ]
