# Generated by Django 2.2.28 on 2025-06-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0258_auto_20250603_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appareil',
            name='periph',
            field=models.CharField(blank=True, choices=[('FOR', 'Front ordinateur'), ('FMO', 'Front smartphone'), ('SUN', 'Sunmi sans imprimante'), ('SU5', 'Sunmi avec imprimante 57mm'), ('SU8', 'Sunmi avec imprimante 80mm'), ('FPI', 'Front Raspberry'), ('SSF', 'Serveur NFC sans front'), ('FSN', 'Front sans lecteur NFC')], max_length=3, null=True),
        ),
    ]
