# Generated by Django 2.2.28 on 2025-06-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0259_auto_20250612_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pointdevente',
            name='comportement',
            field=models.CharField(choices=[('A', 'Vente'), ('C', 'Rechargement'), ('K', 'Kiosque')], default='A', max_length=1),
        ),
    ]
