# Generated by Django 2.2.28 on 2025-06-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0260_auto_20250623_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsintent',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
