# Generated by Django 2.2.28 on 2025-07-07 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0262_paymentsintent_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='appareil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminals', to='APIcashless.Appareil', verbose_name='Appareil lié'),
        ),
    ]
