# Generated by Django 2.2.28 on 2025-08-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0263_terminal_appareil'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlevendu',
            name='metadata',
            field=models.TextField(blank=True, null=True, verbose_name='Metadata'),
        ),
    ]
