# Generated by Django 2.2.28 on 2025-11-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0264_articlevendu_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyenpaiement',
            name='categorie',
            field=models.CharField(choices=[('LE', 'Local'), ('LG', 'Token cadeau'), ('XE', 'Externe'), ('XG', 'Token exterieur cadeau'), ('FD', 'Fedow'), ('CA', 'Espèces'), ('CC', 'Carte bancaire'), ('CH', 'Chèque'), ('TR', 'Bank transfer'), ('NA', 'Offert'), ('FR', 'Fractionné'), ('CM', 'Commande'), ('AR', 'Ardoise'), ('SN', 'En ligne'), ('SF', 'Fédéré'), ('SR', 'Stripe récurrent'), ('QR', 'QrCode ou NFC depuis Lespass'), ('SP', 'Stripe prélèvement SEPA'), ('OC', 'Oceco'), ('BG', 'Badgeuse'), ('XB', 'Badgeuse fédérée'), ('TP', 'Temps'), ('XT', 'Temps fédéré'), ('AD', 'Adhésion associative'), ('MS', 'Abonnement'), ('XM', 'Abonnement fédéré'), ('FI', 'Points de fidélité'), ('XF', 'Points de fidélité fédérés')], default='LE', max_length=2),
        ),
    ]
