# Generated by Django 2.2.28 on 2026-02-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0265_auto_20251125_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nom'),
        ),
    ]
