# Generated by Django 2.2.28 on 2026-01-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0265_auto_20251125_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='currency_code',
        ),
        migrations.AddField(
            model_name='configuration',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
