# Generated by Django 2.2.28 on 2026-01-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0266_auto_20260112_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='currency_code',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
