# Generated by Django 2.2.28 on 2026-05-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0266_auto_20260223_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='lespass_api_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clé API Lespass (adhésions)'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='verifier_adhesion_paiement_nfc',
            field=models.BooleanField(default=False, verbose_name="Vérifier l'adhésion à chaque paiement NFC"),
        ),
    ]
