# Generated by Django 2.2 on 2022-07-12 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ip_lan', models.GenericIPAddressField(blank=True, null=True)),
                ('serveur_impression', models.CharField(blank=True, max_length=100, null=True, verbose_name="Adresse du serveur d'impression")),
                ('api_serveur_impression', models.CharField(blank=True, max_length=50, null=True, verbose_name="Clé d'api pour serveur d'impression")),
            ],
        ),
    ]
