# Generated by Django 2.2 on 2022-08-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsonprinter', '0002_printer_usb_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='thermal_printer_adress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Adresse usb ( ex: 0x04b8,0x0e28 ) ou ip locale de l'imprimante"),
        ),
    ]
