# Generated by Django 2.2 on 2024-12-06 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0247_auto_20241206_1254'),
        ('epsonprinter', '0005_printer_revoquer_odoo_api_serveur_impression'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='APIcashless.Appareil', verbose_name='Appareil hôte'),
        ),
    ]
