# Generated by Django 2.2.28 on 2025-05-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsonprinter', '0007_auto_20250504_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='printer_type',
            field=models.CharField(choices=[('EP', 'Epson via Serveur sur Pi (réseau ou USB) 80mm)'), ('S8', 'Imprimante intégrée aux Sunmi 80mm'), ('S5', 'Imprimante intégrée aux Sunmi 57mm'), ('SC', 'Sunmi Cloud printer 80mm')], default='EP', max_length=2, verbose_name="Type d'imprimante"),
        ),
    ]
