# Generated by Django 4.2 on 2023-10-09 09:04

from django.db import migrations, models
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('laboutik_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=stdimage.models.JPEGField(blank=True, force_min_size=False, null=True, upload_to='users_images', validators=[stdimage.validators.MinSizeValidator(540, 540)], variations={'bg_crop': (1080, 1080, True), 'md_crop': (540, 540, True), 'sm_crop': (270, 270, True)}, verbose_name="Image de profil de l'utilisateur"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='leveling',
            field=models.PositiveIntegerField(choices=[(1, 'Commun'), (2, 'Padawan'), (3, 'Jedi'), (4, 'Sith')], default=1),
        ),
    ]
