# Generated by Django 2.2 on 2022-07-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsonprinter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='usb_adress',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
