# Generated by Django 2.2 on 2021-01-28 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APIcashless', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articlevendu',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articles',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIcashless.Categorie'),
        ),
        migrations.AddField(
            model_name='articles',
            name='couleur_texte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couleur_texte', to='APIcashless.Couleur'),
        ),
        migrations.AddField(
            model_name='articles',
            name='methode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='APIcashless.Methode'),
        ),
        migrations.AddField(
            model_name='articlecommande',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='APIcashless.Articles'),
        ),
        migrations.AddField(
            model_name='articlecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='APIcashless.Commande'),
        ),
        migrations.AddField(
            model_name='appareil',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appairage',
            name='front',
            field=models.OneToOneField(limit_choices_to=models.Q(periph='NFC'), on_delete=django.db.models.deletion.CASCADE, related_name='appareillement_front', to='APIcashless.Appareil'),
        ),
        migrations.AddField(
            model_name='appairage',
            name='lecteur_nfc',
            field=models.OneToOneField(limit_choices_to=models.Q(periph='NFC'), on_delete=django.db.models.deletion.CASCADE, related_name='appareillement_lecteur_nfc', to='APIcashless.Appareil'),
        ),
        migrations.AlterUniqueTogether(
            name='assets',
            unique_together={('monnaie', 'carte')},
        ),
    ]
