# Generated by Django 2.2 on 2021-04-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0007_auto_20210409_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointdevente',
            name='accepte_commandes',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GroupementCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('categories', models.ManyToManyField(related_name='groupements', to='APIcashless.Categorie')),
            ],
        ),
    ]
