# Generated by Django 2.2 on 2021-04-09 07:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0011_auto_20210409_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCommandeSauvegarde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='APIcashless.Articles')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeSauvegarde',
            fields=[
                ('service', models.UUIDField(default=uuid.uuid4)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('O', 'Ouverte'), ('S', 'Servie'), ('P', 'Payée'), ('SP', 'Servie et payée')], default='O', max_length=2)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIcashless.Membre')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='APIcashless.Table')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ('-datetime',),
            },
        ),
        migrations.RemoveField(
            model_name='commande',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='table',
        ),
        migrations.DeleteModel(
            name='ArticleCommande',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.AddField(
            model_name='articlecommandesauvegarde',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='APIcashless.CommandeSauvegarde'),
        ),
    ]
