# Generated by Django 2.2 on 2021-04-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0014_auto_20210409_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportarticlesvendu',
            name='carte_bancaire',
            field=models.SmallIntegerField(default=0, verbose_name='CB'),
        ),
        migrations.AddField(
            model_name='rapportarticlesvendu',
            name='espece',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rapportarticlesvendu',
            name='mollie',
            field=models.SmallIntegerField(default=0, verbose_name='Web (mollie)'),
        ),
        migrations.AddField(
            model_name='rapportarticlesvendu',
            name='monnaie_principale',
            field=models.SmallIntegerField(default=0, verbose_name='Cashless'),
        ),
        migrations.AddField(
            model_name='rapportarticlesvendu',
            name='monnaie_principale_cadeau',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rapportarticlesvendu',
            name='oceco',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rapportarticlesvendu',
            name='qty',
            field=models.SmallIntegerField(default=0),
        ),
    ]
