# Generated by Django 2.2 on 2021-04-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0015_auto_20210409_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationsgraphique',
            options={'verbose_name': 'Graphique du dashboard', 'verbose_name_plural': 'Graphique du dashboard'},
        ),
    ]
