# Generated by Django 2.2 on 2021-04-09 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0004_prefix_hashed_key'),
        ('APIcashless', '0016_auto_20210409_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': 'Configuration générale', 'verbose_name_plural': 'Configuration générale'},
        ),
        migrations.AddField(
            model_name='configuration',
            name='adresse',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='horaire_fermeture',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='horaire_ouverture',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='key',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oceco', to='rest_framework_api_key.APIKey'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='key_billetterie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billetterie', to='rest_framework_api_key.APIKey'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='methode_paiement_fractionne',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration_fractionne', to='APIcashless.Methode'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='moyen_paiement_commande',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_commande', to='APIcashless.MoyenPaiement'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='moyen_paiement_fractionne',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_fractionne', to='APIcashless.MoyenPaiement'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='moyen_paiement_oceco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_oceco', to='APIcashless.MoyenPaiement'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='numero_tva',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='oceco_ip_white_list',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Ip serveur oceco'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='pied_ticket',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='revoquer',
            field=models.BooleanField(default=False, help_text="Selectionnez et validez pour générer ou supprimer une clé API. La clé ne sera affiché qu'a la création, notez la bien !", verbose_name='Créer / Révoquer'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='revoquer_key_billetterie',
            field=models.BooleanField(default=False, help_text="Selectionnez et validez pour générer ou supprimer une clé API. La clé ne sera affiché qu'a la création, notez la bien !", verbose_name='Créer / Révoquer'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='siret',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='structure',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom de la structure'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='taux_tva',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='valeur_oceco',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='emplacement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='methode_adhesion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_adhesion', to='APIcashless.Methode'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='methode_ajout_monnaie_virtuelle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_ajout_monnaie_virtuelle', to='APIcashless.Methode'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='methode_ajout_monnaie_virtuelle_cadeau',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_ajout_monnaie_virtuelle_cadeau', to='APIcashless.Methode'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='methode_retour_consigne',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_retour_consigne', to='APIcashless.Methode'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='methode_vente_article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_vente_article', to='APIcashless.Methode'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='methode_vider_carte',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_vider_carte', to='APIcashless.Methode'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='moyen_paiement_cb',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_cb', to='APIcashless.MoyenPaiement'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='moyen_paiement_espece',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_espece', to='APIcashless.MoyenPaiement'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='moyen_paiement_mollie',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_mollie', to='APIcashless.MoyenPaiement'),
        ),
        migrations.AlterField(
            model_name='rapportbar',
            name='monnaie_encaisse',
            field=models.FloatField(default=0, null=True, verbose_name='Tokens encaissés'),
        ),
        migrations.AlterField(
            model_name='rapportbar',
            name='monnaie_vendu',
            field=models.FloatField(default=0, null=True, verbose_name='Tokens vendus'),
        ),
    ]
