# Generated by Django 2.2 on 2021-04-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0017_auto_20210409_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportbar',
            name='oceco',
            field=models.FloatField(default=0, null=True, verbose_name='Oceco'),
        ),
        migrations.AlterField(
            model_name='rapportbar',
            name='monnaie_encaisse',
            field=models.FloatField(default=0, null=True, verbose_name='Bisiks encaissés'),
        ),
        migrations.AlterField(
            model_name='rapportbar',
            name='monnaie_vendu',
            field=models.FloatField(default=0, null=True, verbose_name='Bisiks vendus'),
        ),
    ]
