# Generated by Django 2.2 on 2021-04-16 09:38

from django.db import migrations
from APIcashless.models import Assets, Membre

from django.core.management import call_command


def last_action(apps, schema_editor):
    # Assets = apps.get_model('APIcashless', 'Assets')
    try:
        call_command('check_last_action')
    except:
        pass

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0022_check_permissions_20210416_1037'),
    ]

    operations = [
        # migrations.RunPython(last_action, reverse),
    ]
