# Generated by Django 2.2 on 2021-04-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0025_pointdevente_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='ephemere',
            field=models.BooleanField(default=False),
        ),
    ]
