# Generated by Django 2.2 on 2021-04-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0026_table_ephemere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
