# Generated by Django 2.2 on 2021-05-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0034_auto_20210506_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartemaitresse',
            name='gift',
            field=models.BooleanField(default=False, verbose_name='Peut offrir une commande'),
        ),
        migrations.AddField(
            model_name='cartemaitresse',
            name='void',
            field=models.BooleanField(default=False, verbose_name='Peut supprimer une commande'),
        ),
    ]
