# Generated by Django 2.2 on 2021-05-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0035_auto_20210510_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartemaitresse',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='cartemaitresse',
            name='void',
        ),
        migrations.AddField(
            model_name='cartemaitresse',
            name='edit_mode',
            field=models.BooleanField(default=False, verbose_name='Peut utiliser le mode édition des commandes'),
        ),
    ]
