# Generated by Django 2.2 on 2021-05-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0036_auto_20210512_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupementcategorie',
            name='thermal_printer_ip_adress',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
