# Generated by Django 2.2 on 2021-05-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0039_auto_20210513_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupementcategorie',
            name='thermal_printer_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name="Adresse ip de l'imprimante CUPS"),
        ),
    ]
