# Generated by Django 2.2 on 2021-05-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0040_groupementcategorie_thermal_printer_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='serveur_cups',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
