# Generated by Django 2.2 on 2021-05-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0042_auto_20210513_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='activer_impression',
            field=models.BooleanField(default=False),
        ),
    ]
