# Generated by Django 2.2 on 2021-05-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0043_configuration_activer_impression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='serveur_cups',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adresse du serveur cups'),
        ),
    ]
