# Generated by Django 2.2 on 2021-05-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0046_auto_20210523_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='serveur_cups',
            new_name='serveur',
        ),
    ]
