# Generated by Django 2.2 on 2021-05-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0054_auto_20210524_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupementcategorie',
            name='qty_ticket',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Nombre de copie à imprimer'),
        ),
    ]
