# Generated by Django 2.2 on 2021-06-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0060_auto_20210524_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='auto_service',
            field=models.BooleanField(default=True),
        ),
    ]
