# Generated by Django 2.2 on 2021-07-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0066_auto_20210710_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandesauvegarde',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
