# Generated by Django 2.2 on 2021-07-10 12:53

from django.db import migrations

from APIcashless.models import CommandeSauvegarde


def archiver(apps, schema_editor):
    for commande in CommandeSauvegarde.objects.filter(archive=False, statut__in=[CommandeSauvegarde.SERVIE_PAYEE,
                                                                                 CommandeSauvegarde.ANNULEE]):
        commande.archive = True
        commande.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('APIcashless', '0067_commandesauvegarde_archive'),
    ]

    operations = [
        migrations.RunPython(archiver, reverse),
    ]
