# Generated by Django 2.2 on 2021-07-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0068_archive_commande_serviepaye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportarticlesvendu',
            name='carte_bancaire',
            field=models.FloatField(default=0, verbose_name='CB'),
        ),
        migrations.AlterField(
            model_name='rapportarticlesvendu',
            name='espece',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rapportarticlesvendu',
            name='mollie',
            field=models.FloatField(default=0, verbose_name='Web (mollie)'),
        ),
        migrations.AlterField(
            model_name='rapportarticlesvendu',
            name='monnaie_principale',
            field=models.FloatField(default=0, verbose_name='Cashless'),
        ),
        migrations.AlterField(
            model_name='rapportarticlesvendu',
            name='monnaie_principale_cadeau',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rapportarticlesvendu',
            name='oceco',
            field=models.FloatField(default=0),
        ),
    ]
