# Generated by Django 2.2 on 2021-07-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0068_archive_commande_serviepaye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='cotisation',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='membre',
            name='paiment_adhesion',
            field=models.CharField(choices=[('E', 'Espece'), ('C', 'CB'), ('G', 'Gratuit'), ('N', "Pas d'adhésion")], default='N', max_length=1, verbose_name='Methode de paiement'),
        ),
    ]
