# Generated by Django 2.2 on 2021-07-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0070_auto_20210727_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportpointsdevente',
            name='remboursement_monnaie_espece',
            field=models.FloatField(default=0, verbose_name='Remboursement'),
        ),
    ]
