# Generated by Django 2.2 on 2021-07-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0074_auto_20210728_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIcashless.Categorie'),
        ),
    ]
