# Generated by Django 2.2 on 2021-09-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0079_pointdevente_service_direct'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='calcul_adhesion',
            field=models.CharField(choices=[('J', '365 Jours'), ('C', '31 Decembre'), ('G', 'Fin année suivante')], default='J', max_length=1, verbose_name="Durée d'adhésion"),
        ),
    ]
