# Generated by Django 2.2 on 2021-09-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0080_configuration_calcul_adhesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='billetterie_ip_white_list',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Ip serveur Billetterie'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='calcul_adhesion',
            field=models.CharField(choices=[('J', '365 Jours'), ('C', '31 Decembre')], default='J', max_length=1, verbose_name="Durée d'adhésion"),
        ),
    ]
