# Generated by Django 2.2 on 2021-10-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0083_auto_20210927_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='calcul_adhesion',
            field=models.CharField(choices=[('J', '365 Jours'), ('C', '31 Decembre'), ('G', 'Année glissante : Octobre -> Decembre +1')], default='J', max_length=1, verbose_name="Durée d'adhésion"),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='prix_adhesion',
            field=models.SmallIntegerField(default=20, verbose_name="Prix de l'adhésion par default"),
        ),
        migrations.AlterField(
            model_name='membre',
            name='adhesion_origine',
            field=models.CharField(choices=[('A', 'Depuis Admin'), ('F', 'Front Cashless'), ('Q', 'Scan QR Code'), ('B', 'Billetterie'), ('H', 'HelloAsso')], default='A', max_length=1, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='cotisation',
            field=models.FloatField(default=20, help_text='Vous pouvez modifier la valeur par default dans la page de configuration générale'),
        ),
    ]
