# Generated by Django 2.2 on 2021-10-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0085_auto_20211005_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapporttableaucomptable',
            name='adhesion_carte_bancaire',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rapporttableaucomptable',
            name='adhesion_espece',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rapporttableaucomptable',
            name='adhesion_stripe',
            field=models.FloatField(default=0),
        ),
    ]
