# Generated by Django 2.2 on 2021-10-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0086_auto_20211005_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapporttableaucomptable_pos',
            name='monnaie',
        ),
    ]
