# Generated by Django 2.2 on 2021-10-06 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0088_delete_rapporttableaucomptable_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportTableauComptable_POS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depense', models.FloatField(default=0)),
                ('monnaie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIcashless.MoyenPaiement')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIcashless.PointDeVente')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses_par_POS', to='APIcashless.RapportTableauComptable')),
            ],
        ),
    ]
