# Generated by Django 2.2 on 2021-10-12 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0085_auto_20211006_1656'),
        ('APIcashless', '0092_rapporttableaucomptable_rapporttableaucomptable_pos'),
    ]

    operations = [
    ]
