# Generated by Django 2.2 on 2021-11-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0099_configuration_domaine_cashless'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapporttableaucomptable',
            name='monnaie_restante_calcul_rapport',
            field=models.FloatField(default=0),
        ),
    ]
