# Generated by Django 2.2 on 2021-11-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0101_rapporttableaucomptable_cadeau_restant_calcul_rapport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RapportBar',
        ),
    ]
