# Generated by Django 2.2 on 2022-02-17 06:36

from django.db import migrations

from APIcashless.models import Configuration, Articles


def methode_to_choice(apps, schema_editor):
    '''
    Applique les configuration.methode sur les choices directement.
    try :
        config = Configuration.get_solo()
        if config.methode_adhesion and \
            config.methode_vente_article and \
            config.methode_retour_consigne and \
            config.methode_vider_carte and \
            config.methode_paiement_fractionne and \
            config.methode_ajout_monnaie_virtuelle_cadeau and \
            config.methode_ajout_monnaie_virtuelle :

            for article in Articles.objects.all():
                if article.methode == config.methode_adhesion:
                    article.methode_choices = Articles.ADHESIONS
                elif article.methode == config.methode_vente_article:
                    article.methode_choices = Articles.VENTE
                elif article.methode == config.methode_retour_consigne:
                    article.methode_choices = Articles.RETOUR_CONSIGNE
                elif article.methode == config.methode_vider_carte:
                    article.methode_choices = Articles.VIDER_CARTE
                elif article.methode == config.methode_paiement_fractionne:
                    article.methode_choices = Articles.FRACTIONNE
                elif article.methode == config.methode_ajout_monnaie_virtuelle_cadeau:
                    article.methode_choices = Articles.RECHARGE_CADEAU
                elif article.methode == config.methode_ajout_monnaie_virtuelle:
                    article.methode_choices = Articles.RECHARGE_EUROS
                print(f"{article.name} - {article.methode} -> {article.methode_choices} ")
                article.save()
    except:
        pass
    '''
    pass

def reverse(*args, **kwargs):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0108_articles_methode_choices'),
    ]

    operations = [
        migrations.RunPython(methode_to_choice, reverse),

    ]
