# Generated by Django 2.2 on 2022-03-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0111_auto_20220330_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='odoo_database',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
