# Generated by Django 2.2 on 2022-03-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0114_auto_20220330_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odoologs',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
