# Generated by Django 2.2 on 2022-07-01 10:26

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0116_auto_20220427_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images/', validators=[stdimage.validators.MaxSizeValidator(200, 200)], variations={'thumbnail': (60, 60)}),
        ),
    ]
