# Generated by Django 2.2 on 2022-08-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0121_auto_20220816_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='activer_impression',
        ),
        migrations.RemoveField(
            model_name='groupementcategorie',
            name='activer_impression',
        ),
        migrations.RemoveField(
            model_name='groupementcategorie',
            name='api_serveur_impression',
        ),
        migrations.RemoveField(
            model_name='groupementcategorie',
            name='serveur_impression',
        ),
        migrations.RemoveField(
            model_name='groupementcategorie',
            name='thermal_printer_adress',
        ),
        migrations.RemoveField(
            model_name='groupementcategorie',
            name='thermal_printer_name',
        ),
    ]
