# Generated by Django 2.2 on 2022-08-16 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsonprinter', '0004_auto_20220816_1228'),
        ('APIcashless', '0122_auto_20220816_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='direct_to_printer',
            field=models.ForeignKey(blank=True, help_text='Direct sur imprimante choisie à chaque vente.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='epsonprinter.Printer'),
        ),
    ]
