# Generated by Django 2.2 on 2022-08-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0123_articles_direct_to_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='decompte_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articles',
            name='direct_to_printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epsonprinter.Printer'),
        ),
    ]
