# Generated by Django 2.2 on 2022-08-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0124_auto_20220816_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='decompte_ticket',
            field=models.BooleanField(default=False, help_text='Incrémente le décompte des billets vendu à la journée et imprimé sur le ticket.'),
        ),
    ]
