# Generated by Django 2.2 on 2022-08-25 08:01

# Generated by Django 2.2 on 2021-04-16 06:37
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations
from django.core.management import call_command
from APIcashless.models import CarteCashless


def check_permission(apps, schema_editor):
    # se refferer au JET_SIDE_MENU_ITEMS dans settings.
    '''
    content_type = ContentType.objects.get_for_model(CarteCashless)
    p = Permission.objects.filter(
        content_type=content_type,
        )
    for x in p:
        print(x.codename)
    '''

    # call_command('check_permissions')
    pass



def reverse(apps, schema_editor):
    try:
        staff_group = Group.objects.get(name="staff")
        for p in staff_group.permissions.all():
            staff_group.permissions.remove(p)
    except:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0126_articlevendu_uuid_paiement'),
    ]

    operations = [
            migrations.RunPython(check_permission, reverse),
    ]


