# Generated by Django 2.2 on 2022-09-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0131_auto_20220923_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlevendu',
            name='pos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='APIcashless.PointDeVente'),
        ),
    ]
