# Generated by Django 2.2 on 2022-09-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0136_auto_20220924_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecommandesauvegarde',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='articlecommandesauvegarde',
            name='reste_a_payer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='articlecommandesauvegarde',
            name='reste_a_servir',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='cashback_start',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Valeur du rechargement en ligne à partir de laquelle les cadeaux s'enclenchent", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='cashback_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valeur donnée en monnaie cadeau', max_digits=10, null=True),
        ),
    ]
