# Generated by Django 2.2 on 2022-09-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0137_auto_20220924_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlevendu',
            name='qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True),
        ),
    ]
