# Generated by Django 2.2 on 2022-10-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0138_auto_20220925_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartecashless',
            name='recharge_suspendue',
            field=models.BooleanField(default=False),
        ),
    ]
