# Generated by Django 2.2 on 2022-12-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0141_configuration_billetterie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='federated_currency',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_federated', to='APIcashless.MoyenPaiement'),
        ),
        migrations.AddField(
            model_name='moyenpaiement',
            name='categorie',
            field=models.CharField(choices=[('LE', 'Token local €'), ('LG', 'Token local cadeau'), ('SF', 'Token Federated Stripe')], default='LE', max_length=2),
        ),
        migrations.AlterField(
            model_name='articlevendu',
            name='carte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='APIcashless.CarteCashless'),
        ),
        migrations.AlterField(
            model_name='articlevendu',
            name='membre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='APIcashless.Membre'),
        ),
        migrations.AlterField(
            model_name='articlevendu',
            name='moyen_paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='APIcashless.MoyenPaiement'),
        ),
        migrations.AlterField(
            model_name='articlevendu',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles_vendus_responsables', to='APIcashless.Membre'),
        ),
    ]
