# Generated by Django 2.2 on 2023-01-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0143_asset_federated_20221220_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='methode_choices',
            field=models.CharField(choices=[('VT', 'Vente'), ('RS', 'RechargeS'), ('RE', 'Recharge €'), ('RF', 'Recharge fédérée €'), ('RC', 'Recharge Cadeau'), ('AD', 'Adhésions'), ('CR', 'Retour de consigne'), ('VC', 'Vider Carte'), ('BC', 'Blanchir Carte'), ('VV', 'Void Carte'), ('FR', 'Fractionné'), ('BI', 'Billet de concert')], default='VT', max_length=2),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='billetterie_url',
            field=models.URLField(default='https://www.tibillet.re', verbose_name='Url du serveur SaaS'),
        ),
        migrations.AlterField(
            model_name='moyenpaiement',
            name='categorie',
            field=models.CharField(choices=[('LE', 'Token local €'), ('LG', 'Token local cadeau'), ('SF', 'Token Federated Stripe'), ('CA', 'Espèces'), ('CC', 'Carte bancaire TPE')], default='LE', max_length=2),
        ),
    ]
