# Generated by Django 2.2 on 2023-01-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0150_EX_manual_moyenpaiement_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='asset_categorie',
        ),
    ]
