# Generated by Django 2.2 on 2023-04-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0158_auto_20230406_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapporttableaucomptable',
            name='cash_float',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fond de caisse.'),
        ),
    ]
