# Generated by Django 2.2 on 2023-05-04 16:11

from django.db import migrations

from APIcashless.models import ArticleVendu, Categorie


def add_category_to_old_sold(apps, schema_editor):
        articles_m_vente = ArticleVendu.objects.all()
        categories = Categorie.objects.all()
        print("On mets à jour les catégories des articles vendus")
        for categorie in categories:
            print(f"    {categorie}")
            articles_m_vente.filter(article__categorie=categorie).update(categorie=categorie)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0163_articlevendu_categorie'),
    ]

    operations = [
        migrations.RunPython(add_category_to_old_sold, reverse),
    ]
