# Generated by Django 2.2 on 2023-07-18 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0170_auto_20230717_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloturecaisse',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fermeture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ouverture'),
            preserve_default=False,
        ),
    ]
