# Generated by Django 2.2 on 2023-07-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0175_auto_20230725_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapporttableaucomptable',
            options={'ordering': ('-date',), 'verbose_name': 'EX Tableau comptable', 'verbose_name_plural': 'EX Tableaux comptable'},
        ),
        migrations.AlterField(
            model_name='configuration',
            name='cashback_active',
            field=models.BooleanField(default=False, verbose_name='Activez le cashbash pour les rechargements cashless'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='cashback_start',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Valeur du rechargement à partir de laquelle les cadeaux s'enclenchent", max_digits=10, null=True),
        ),
    ]
