# Generated by Django 2.2 on 2023-08-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0180_auto_20230822_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='fedow_key',
            new_name='fedow_api_key',
        ),
        migrations.AddField(
            model_name='configuration',
            name='fedow_public_rsa_key',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
    ]
