# Generated by Django 2.2 on 2023-10-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0183_auto_20231006_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='fedow_place_wallet_public_pem',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
