# Generated by Django 2.2 on 2023-10-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0185_auto_20231011_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyenpaiement',
            name='categorie',
            field=models.CharField(choices=[('LE', 'Token local €'), ('LG', 'Token local cadeau'), ('FR', 'Fractionné'), ('SF', 'Stripe'), ('XT', 'Token fédéré exterieur €'), ('FD', 'Fedow'), ('SN', 'Web (Stripe)'), ('CA', 'Espèces'), ('CC', 'Carte bancaire'), ('CH', 'Cheque'), ('OC', 'Oceco'), ('AR', 'Ardoise'), ('CM', 'Commande')], default='LE', max_length=2),
        ),
    ]
