# Generated by Django 2.2 on 2023-10-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0186_auto_20231018_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='fedow_place_wallet_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
