# Generated by Django 2.2 on 2023-10-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0189_remove_configuration_federated_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
