# Generated by Django 2.2 on 2023-11-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0191_auto_20231116_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='wallet',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
