# Generated by Django 2.2 on 2023-12-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0194_auto_20231204_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartemaitresse',
            name='carte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartes_maitresses', to='APIcashless.CarteCashless', unique=True),
        ),
        migrations.AlterField(
            model_name='moyenpaiement',
            name='categorie',
            field=models.CharField(choices=[('LE', 'Token local €'), ('LG', 'Token local cadeau'), ('FR', 'Fractionné'), ('SF', 'Stripe'), ('XT', 'Token fédéré exterieur €'), ('XG', 'Token fédéré cadeau'), ('FD', 'Fedow'), ('SN', 'Web (Stripe)'), ('CA', 'Espèces'), ('CC', 'Carte bancaire'), ('CH', 'Cheque'), ('OC', 'Oceco'), ('AR', 'Ardoise'), ('CM', 'Commande'), ('BG', 'Badgeuse'), ('TP', 'Temps'), ('AD', 'Adhésion associative'), ('MS', 'Abonnement')], default='LE', max_length=2),
        ),
    ]
