# Generated by Django 2.2 on 2023-12-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0198_cartecashless_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='wallet',
        ),
    ]
