# Generated by Django 2.2 on 2023-12-22 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0199_remove_membre_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membre', to='APIcashless.Wallet'),
        ),
    ]
