# Generated by Django 2.2 on 2024-01-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0201_articles_subscription_fedow_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlevendu',
            name='sync_fedow',
            field=models.BooleanField(default=False, verbose_name='Fedow'),
        ),
        migrations.AlterField(
            model_name='moyenpaiement',
            name='categorie',
            field=models.CharField(choices=[('LE', 'Token local €'), ('LG', 'Token local cadeau'), ('FR', 'Fractionné'), ('SF', 'Stripe'), ('XT', 'Token fédéré exterieur €'), ('XG', 'Token fédéré cadeau'), ('FD', 'Fedow'), ('SN', 'Web (Stripe)'), ('CA', 'Espèces'), ('CC', 'Carte bancaire'), ('CH', 'Cheque'), ('OC', 'Oceco'), ('AR', 'Ardoise'), ('CM', 'Commande'), ('BG', 'Badgeuse'), ('XB', 'Badgeuse fédérée'), ('TP', 'Temps'), ('XT', 'Temps fédéré'), ('AD', 'Adhésion associative'), ('MS', 'Abonnement'), ('XM', 'Abonnement fédéré')], default='LE', max_length=2),
        ),
    ]
