# Generated by Django 2.2 on 2024-01-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0207_auto_20240127_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlevendu',
            name='hash_fedow',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
