# Generated by Django 2.2 on 2024-01-30 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0209_auto_20240128_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='fidelity_active',
            field=models.BooleanField(default=False, verbose_name='Incrémentez des points de fidélité pour chaque achats.'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='fidelity_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIcashless.MoyenPaiement', verbose_name='Asset de fidélité'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='fidelity_asset_trigger',
            field=models.ManyToManyField(blank=True, null=True, related_name='fidelity_asset_trigger', to='APIcashless.MoyenPaiement', verbose_name="Asset déclencheur de l'incrémentation des points de fidélité"),
        ),
        migrations.AddField(
            model_name='configuration',
            name='fidelity_factor',
            field=models.DecimalField(decimal_places=2, default=1, help_text='10€ de vente X facteur = X*10 points de fidélité.', max_digits=4, verbose_name='Facteur de point.'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='methode_choices',
            field=models.CharField(choices=[('VT', 'Vente'), ('RE', 'Recharge €'), ('RF', 'Recharge fédérée €'), ('RC', 'Recharge Cadeau'), ('AD', 'Adhésions'), ('CR', 'Retour de consigne'), ('VC', 'Vider Carte'), ('BC', 'Blanchir Carte'), ('VV', 'Void Carte'), ('FR', 'Fractionné'), ('BI', 'Billet de concert'), ('BG', 'Badgeuse'), ('FD', 'Fidélité')], default='VT', max_length=2),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='monnaies_acceptes',
            field=models.ManyToManyField(blank=True, related_name='configuration_monnaies_acceptees', to='APIcashless.MoyenPaiement', verbose_name='Monnaies Acceptées'),
        ),
        migrations.AlterField(
            model_name='moyenpaiement',
            name='categorie',
            field=models.CharField(choices=[('LE', 'Token local €'), ('LG', 'Token local cadeau'), ('FR', 'Fractionné'), ('SF', 'Stripe'), ('XT', 'Token fédéré exterieur €'), ('XG', 'Token fédéré cadeau'), ('FD', 'Fedow'), ('SN', 'Web (Stripe)'), ('CA', 'Espèces'), ('CC', 'Carte bancaire'), ('CH', 'Cheque'), ('OC', 'Oceco'), ('AR', 'Ardoise'), ('CM', 'Commande'), ('BG', 'Badgeuse'), ('XB', 'Badgeuse fédérée'), ('TP', 'Temps'), ('XT', 'Temps fédéré'), ('AD', 'Adhésion associative'), ('MS', 'Abonnement'), ('XM', 'Abonnement fédéré'), ('FI', 'Points de fidélité'), ('XF', 'Points de fidélité fédérés')], default='LE', max_length=2),
        ),
    ]
