# Generated by Django 2.2 on 2024-01-30 10:27

from django.db import migrations

def create_fidelity_asset(apps, schema_editor):
        MoyenPaiement = apps.get_model('APIcashless', 'MoyenPaiement')
        try :
            fidelity = MoyenPaiement.objects.get(categorie='FI')
        except MoyenPaiement.DoesNotExist:
            fidelity = MoyenPaiement.objects.create(categorie='FI', name="Fidelity")


def reverse(apps, schema_editor):
    MoyenPaiement = apps.get_model('APIcashless', 'MoyenPaiement')
    try:
        fidelity = MoyenPaiement.objects.get(categorie='FI')
        fidelity.delete()
    except MoyenPaiement.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0210_auto_20240130_1427'),
    ]

    operations = [
        migrations.RunPython(create_fidelity_asset, reverse),
    ]
