# Generated by Django 2.2 on 2024-02-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0213_auto_20240201_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': 'Configuration', 'verbose_name_plural': 'Configuration'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIcashless.Categorie', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='monnaies_acceptes',
            field=models.ManyToManyField(blank=True, related_name='configuration_monnaies_acceptees', to='APIcashless.MoyenPaiement', verbose_name='Assets acceptés pour ventes'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='prix_adhesion',
            field=models.SmallIntegerField(default=0, verbose_name="Prix de l'adhésion par default"),
        ),
        migrations.AlterField(
            model_name='groupementcategorie',
            name='categories',
            field=models.ManyToManyField(related_name='groupements', to='APIcashless.Categorie', verbose_name='Catégories'),
        ),
    ]
