# Generated by Django 2.2 on 2024-02-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0214_auto_20240206_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='badgeuse_active',
            field=models.BooleanField(default=False, verbose_name='Badgeuse active'),
        ),
        migrations.AlterField(
            model_name='articlevendu',
            name='comptabilise',
            field=models.BooleanField(default=False, verbose_name='Envoyé sur Odoo'),
        ),
    ]
