# Generated by Django 2.2 on 2024-02-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0216_auto_20240216_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='journal_out_invoice',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du journal Facture Client'),
        ),
    ]
