# Generated by Django 2.2 on 2024-02-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0219_auto_20240223_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='appareil',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='appareil',
            name='pin_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Code PIN, valide 10 minutes.'),
        ),
    ]
