# Generated by Django 2.2 on 2024-02-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0220_auto_20240223_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='discovery_key',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Clé API Serveur de découverte'),
        ),
        migrations.AlterField(
            model_name='appareil',
            name='pin_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Code PIN'),
        ),
    ]
