# Generated by Django 2.2 on 2024-02-26 10:52
from django.core.management import call_command
from django.db import migrations, models


def set_bad_ip(apps, schema_editor):
    Appareil = apps.get_model('APIcashless', 'Appareil')
    Appareil.objects.filter(ip_lan='987.987.987.987').update(ip_lan='127.0.0.1')


def check_permissions(apps, schema_editor):
    call_command('check_permissions')


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('APIcashless', '0221_auto_20240224_1917'),
    ]

    operations = [
        migrations.RunPython(set_bad_ip, reverse),

        migrations.AddField(
            model_name='appareil',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appareil',
            name='ip_wan',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appareil',
            name='ip_lan',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),

        migrations.RunPython(check_permissions, reverse),
    ]
