# Generated by Django 2.2 on 2024-04-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcashless', '0224_appareil_user_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appareil',
            old_name='apk_version',
            new_name='version',
        ),
    ]
