# Generated by Django 2.2 on 2024-05-13 12:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APIcashless', '0225_auto_20240404_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedNfcCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIcashless.CarteCashless')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('saved_at', models.DateTimeField(auto_now=True, verbose_name='saved at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Somme souhaitée')),
                ('device_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Somme insérée dans la machine')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kiosk_payment', to='APIcashless.CarteCashless', verbose_name='Carte')),
            ],
        ),
    ]
